### PR TITLE
Update UnityInputDeviceProfile.cs

### PR DESCRIPTION
**Pull request by Flag74**
added AddInputControlMapping method

### CODE REVIEW

**Comment by pbhogan** [comment]
`AnalogMappings` and `ButtonMappings` are expected to be immutable or they would be `List< InputControlMapping >` and have a public setter.

**Comment by aggsol** [comment]
@pbhogan I did not think about it that way. Care to explain your rationale? Setting a user customized mapping that way looks easy. Any caveats?

**Comment by pbhogan** [comment]
The rationale is simply that the rest of the internals currently expect device profiles to be hardcoded, loaded at InControl setup and be immutable. Once a device instance is created from a profile, the profile is not consulted further so changing it is pointless and profile can't currently be added after setup. The purpose of profiles is to map a device, not allow user mappings (yet).

I tend to make the API reenforce the fact that currently unsupported features are truly *unsupported* and hacks to get around the API are a bad idea because they will break as I change internals. If the API seems to make something possible then people expect it to work.

All that said, I am working on a fairly substantial update that adds features for user rebindings (which has nothing to do with profiles) and also loading device profiles from external files allowing users to map controllers InControl doesn't have a built-in profile for yet.

**Comment by aggsol** [comment]
@pbhogan Thank you for your clarifications! Keep up the good work.

**Pull request closed without merging**
